// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

import './App.css';
;

function App(Props) {
  return React.createElement("div", {
              className: "App"
            }, React.createElement("header", {
                  className: "App-header"
                }, React.createElement("p", undefined, "Edit ", React.createElement("code", undefined, "src/App.res"), " and save to reload.")));
}

var make = App;

export {
  make ,
  
}
/*  Not a pure module */
