// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import LogoSvg from "./logo.svg";
import * as Square$RescriptReactIntro from "./Square.bs.js";

import './App.css';
;

var logo = LogoSvg;

function App(Props) {
  return React.createElement("div", {
              className: "App"
            }, React.createElement(Square$RescriptReactIntro.make, {}), React.createElement("header", {
                  className: "App-header"
                }, React.createElement("p", undefined, "Edit ", React.createElement("code", undefined, "src/App.res"), " and save to reload.")));
}

var make = App;

export {
  logo ,
  make ,
  
}
/*  Not a pure module */
