// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Store$RescriptReactIntro from "./Store.bs.js";
import * as Target$RescriptReactIntro from "./Target.bs.js";
import * as Target2$RescriptReactIntro from "./Target2.bs.js";
import * as Controls$RescriptReactIntro from "./Controls.bs.js";

import './App.css';
;

function AppMain(Props) {
  var match = React.useReducer(Store$RescriptReactIntro.reducer, Store$RescriptReactIntro.initialState);
  var dispatch = match[1];
  var state = match[0];
  React.useEffect((function () {
          Curry._1(dispatch, /* ChangeValue */{
                counter: 113
              });
          
        }), [dispatch]);
  return React.createElement("div", undefined, React.createElement(Controls$RescriptReactIntro.make, {
                  state: state,
                  dispatch: dispatch
                }), React.createElement("hr", undefined), React.createElement(Target$RescriptReactIntro.make, {
                  state: state,
                  dispatch: dispatch
                }), React.createElement("hr", undefined), React.createElement(Target2$RescriptReactIntro.make, {
                  state: state,
                  dispatch: dispatch
                }), React.createElement("hr", undefined), React.createElement("hr", undefined));
}

var make = AppMain;

export {
  make ,
  
}
/*  Not a pure module */
