// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

function Controls(Props) {
  var state = Props.state;
  var dispatch = Props.dispatch;
  return React.createElement("main", undefined, React.createElement("div", {
                  className: "Controls"
                }, React.createElement("header", {
                      className: "Controls-header"
                    }, React.createElement("div", undefined, React.createElement("button", {
                              onClick: (function (param) {
                                  return Curry._1(dispatch, /* ChangeValue */{
                                              counter: state.data.counter - 10 | 0
                                            });
                                })
                            }, "Decrement"), React.createElement("span", {
                              className: "counter"
                            }, String(state.data.counter)), React.createElement("button", {
                              onClick: (function (param) {
                                  return Curry._1(dispatch, /* ChangeValue */{
                                              counter: state.data.counter + 10 | 0
                                            });
                                })
                            }, "Increment")))));
}

var make = Controls;

export {
  make ,
  
}
/* react Not a pure module */
