// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Pervasives from "rescript/lib/es6/pervasives.js";

function Display(Props) {
  var state = Props.state;
  return React.createElement("main", undefined, React.createElement("div", {
                  className: "Display"
                }, React.createElement("header", {
                      className: "Display-header"
                    }, React.createElement("div", undefined, React.createElement("span", {
                              className: "counter"
                            }, "Counter: " + String(state.data.counter)), React.createElement("br", undefined), React.createElement("span", undefined, "Thickness: " + state.data.thickness.toString()), React.createElement("br", undefined), React.createElement("span", undefined, "Width: " + state.data.width.toString()), React.createElement("br", undefined), React.createElement("span", undefined, "Depth: " + state.data.depth.toString()), React.createElement("br", undefined), React.createElement("span", undefined, "Height: " + state.data.height.toString()), React.createElement("br", undefined), React.createElement("span", undefined, "Enclosed?: " + Pervasives.string_of_bool(state.data.includeEnclosure)), React.createElement("br", undefined), React.createElement("span", undefined, "Dip Fraction: " + state.data.dipFraction.toString()), React.createElement("br", undefined)), React.createElement("hr", undefined))));
}

var make = Display;

export {
  make ,
  
}
/* react Not a pure module */
