// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Target2$RescriptReactIntro from "./Target2.bs.js";

function Scrap(Props) {
  return React.createElement("main", undefined, React.createElement("div", {
                  className: "Scrap"
                }, React.createElement("header", {
                      className: "Scrap-header"
                    }, React.createElement("div", undefined, React.createElement("button", undefined, "Show width"), React.createElement("span", {
                              className: "width"
                            }, String(Target2$RescriptReactIntro.getValue(undefined)))))));
}

var make = Scrap;

export {
  make ,
  
}
/* react Not a pure module */
