// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Reprocessing from "reprocessing/src/Reprocessing.bs.js";
import * as Reprocessing_Env from "reprocessing/src/Reprocessing_Env.bs.js";
import * as Reprocessing_Draw from "reprocessing/src/Reprocessing_Draw.bs.js";
import * as Reprocessing_Constants from "reprocessing/src/Reprocessing_Constants.bs.js";

function setup(env) {
  return Reprocessing_Env.size(200, 200, env);
}

function draw(_state, env) {
  Reprocessing_Draw.background(Reprocessing_Constants.red, env);
  Reprocessing_Draw.fill(Reprocessing_Constants.green, env);
  return Reprocessing_Draw.rect([
              50,
              50
            ], 100, 100, env);
}

Reprocessing.run(setup, undefined, draw, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);

export {
  setup ,
  draw ,
  
}
/*  Not a pure module */
