// Generated by ReScript, PLEASE EDIT WITH CARE


function updateCounter(count) {
  return {
          data: {
            counter: count
          },
          svg: ""
        };
}

function reducer(state, action) {
  return {
          data: {
            counter: action.counter
          },
          svg: ""
        };
}

var initialState = {
  data: {
    counter: 100
  },
  svg: ""
};

export {
  initialState ,
  updateCounter ,
  reducer ,
  
}
/* No side effect */
