// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Reprocessing from "reprocessing/src/Reprocessing.bs.js";
import * as Reprocessing_Env from "reprocessing/src/Reprocessing_Env.bs.js";
import * as Reprocessing_Draw from "reprocessing/src/Reprocessing_Draw.bs.js";
import * as Reprocessing_Constants from "reprocessing/src/Reprocessing_Constants.bs.js";

function Target2(Props) {
  var state = Props.state;
  var id = "reprocessing-square";
  var setup = function (env) {
    return Reprocessing_Env.size(200, 200, env);
  };
  var draw = function (_state, env) {
    Reprocessing_Draw.background(Reprocessing_Constants.red, env);
    Reprocessing_Draw.fill(Reprocessing_Constants.green, env);
    return Reprocessing_Draw.rect([
                50,
                50
              ], state.data.counter, 100, env);
  };
  React.useEffect(function () {
        Reprocessing.setScreenId(id);
        Reprocessing.run(setup, undefined, draw, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
        
      });
  return React.createElement("canvas", {
              id: id
            });
}

var make = Target2;

export {
  make ,
  
}
/* react Not a pure module */
